In [111]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [112]:
df= pd.read_csv("cust_satisfaction.csv")
df.head()

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,Female,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,Male,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Gender                      103904 non-null  object
 1   Customer Type               103904 non-null  object
 2   Type of Travel              103904 non-null  object
 3   Class                       103904 non-null  object
 4   satisfaction                103904 non-null  object
 5   Age                         103904 non-null  int64
 6   Flight Distance             103904 non-null  int64
 7   Inflight entertainment      103904 non-null  int64
 8   Baggage handling            103904 non-null  int64
 9   Cleanliness                 103904 non-null  int64
 10  Departure Delay in Minutes  103904 non-null  int64
 11  Arrival Delay in Minutes    103594 non-null  float64
dtypes: float64(1), int64(6), object(5)
memory usage: 9.5+ MB

In [114]:
df.dropna(inplace= True)
df.isnull().sum()

Gender                        0
Customer Type                 0
Type of Travel                0
Class                         0
satisfaction                  0
Age                           0
Flight Distance               0
Inflight entertainment        0
Baggage handling              0
Cleanliness                   0
Departure Delay in Minutes    0
Arrival Delay in Minutes      0
dtype: int64

In [115]:
df.drop_duplicates(inplace = True)    
df.duplicated().sum()
df.drop_duplicates()

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,Female,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,Male,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,Male,Loyal Customer,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,Male,Loyal Customer,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0

In [116]:
df["Customer Type"].value_counts()

Customer Type
Loyal Customer       84517
disloyal Customer    18905
Name: count, dtype: int64

In [117]:
loyal_customer = df[df["Customer Type"] == "Loyal Customer"]
disloyal_customer=df[df["Customer Type"] == "disloyal Customer"]

In [118]:
loyal_customer = loyal_customer.sample(20000)
loyal_customer.shape

(20000, 12)

In [119]:
balance_df = pd.concat([loyal_customer,disloyal_customer],axis=0)
balance_df.shape

(38905, 12)

In [120]:
cat_col = balance_df.select_dtypes(include=["object"])
cat_col.head()

,Gender,Customer Type,Type of Travel,Class,satisfaction
101398,Male,Loyal Customer,Business travel,Business,neutral or dissatisfied
78587,Female,Loyal Customer,Business travel,Business,satisfied
90985,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied
99826,Female,Loyal Customer,Business travel,Business,satisfied
78022,Male,Loyal Customer,Business travel,Business,satisfied

In [121]:
num_col = balance_df.select_dtypes(exclude=['object'])
num_col.head()

,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
101398,36,2951,3,3,1,0,4.0
78587,50,2360,4,4,3,13,17.0
90985,39,3660,4,4,1,65,55.0
99826,40,2704,5,5,3,17,0.0
78022,45,1107,2,2,5,0,0.0

In [122]:
pd.get_dummies(cat_col).astype(int).head()

,Gender_Female,Gender_Male,Customer Type_Loyal Customer,Customer Type_disloyal Customer,Type of Travel_Business travel,Type of Travel_Personal Travel,Class_Business,Class_Eco,Class_Eco Plus,satisfaction_neutral or dissatisfied,satisfaction_satisfied
101398,0,1,1,0,1,0,1,0,0,1,0
78587,1,0,1,0,1,0,1,0,0,0,1
90985,1,0,1,0,1,0,1,0,0,1,0
99826,1,0,1,0,1,0,1,0,0,0,1
78022,0,1,1,0,1,0,1,0,0,0,1

In [123]:
pd.get_dummies(cat_col,drop_first=True).astype(int).head()

,Gender_Male,Customer Type_disloyal Customer,Type of Travel_Personal Travel,Class_Eco,Class_Eco Plus,satisfaction_satisfied
101398,1,0,0,0,0,0
78587,0,0,0,0,0,1
90985,0,0,0,0,0,0
99826,0,0,0,0,0,1
78022,1,0,0,0,0,1

In [124]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

ohe = OneHotEncoder(drop="if_binary")
cat_col_encoded = ohe.fit_transform(cat_col).toarray()
cat_col_encoded

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 1., 0., 0.],
       [1., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.]])

In [125]:
column_name = list(ohe.get_feature_names_out())
column_name

['Gender_Male',
 'Customer Type_disloyal Customer',
 'Type of Travel_Personal Travel',
 'Class_Business',
 'Class_Eco',
 'Class_Eco Plus',
 'satisfaction_satisfied']

In [126]:
one_hot = pd.DataFrame(cat_col_encoded,columns=column_name)
one_hot.head()

,Gender_Male,Customer Type_disloyal Customer,Type of Travel_Personal Travel,Class_Business,Class_Eco,Class_Eco Plus,satisfaction_satisfied
0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,1.0,0.0,0.0,1.0,0.0,0.0,1.0

In [127]:
one_hot = one_hot.reset_index(drop=True)
num_col = num_col.reset_index(drop=True)
final_df = pd.concat([one_hot,num_col],axis=1)
final_df.head()

,Gender_Male,Customer Type_disloyal Customer,Type of Travel_Personal Travel,Class_Business,Class_Eco,Class_Eco Plus,satisfaction_satisfied,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,36,2951,3,3,1,0,4.0
1,0.0,0.0,0.0,1.0,0.0,0.0,1.0,50,2360,4,4,3,13,17.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,39,3660,4,4,1,65,55.0
3,0.0,0.0,0.0,1.0,0.0,0.0,1.0,40,2704,5,5,3,17,0.0
4,1.0,0.0,0.0,1.0,0.0,0.0,1.0,45,1107,2,2,5,0,0.0

In [128]:
## x and y --->train test split
x = final_df.drop('satisfaction_satisfied',axis=1)
y = final_df['satisfaction_satisfied']

In [129]:
## training and testing
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test = train_test_split(x , y, 
                                                  test_size=0.2,
                                                  random_state=42)

In [130]:
from sklearn.linear_model import LogisticRegression
lor = LogisticRegression()
lor.fit(x_train,y_train)

C:\Users\uma13\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [131]:
lor.score(x_train,y_train)

0.7650044981364863

In [132]:
lor.score(x_test,y_test)

0.7664824572677034

In [133]:
y_pred = lor.predict(x_test)
y_pred

array([1., 0., 0., ..., 0., 0., 1.])

In [134]:
df1= pd.DataFrame({'Actual':y_test,'Predicted':y_pred})
df1

       Actual  Predicted
18536     1.0        1.0
36240     0.0        0.0
5426      1.0        0.0
21679     1.0        0.0
18714     0.0        0.0
...       ...        ...
23667     0.0        0.0
9774      0.0        0.0
24880     0.0        0.0
38451     1.0        0.0
8362      1.0        1.0

[7781 rows x 2 columns]

In [135]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))

[[4183  822]
 [ 995 1781]]

In [136]:
## confusion matrix
# accuracy, precision , recall ,f1-score

In [137]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.81      0.84      0.82      5005
         1.0       0.68      0.64      0.66      2776

    accuracy                           0.77      7781
   macro avg       0.75      0.74      0.74      7781
weighted avg       0.76      0.77      0.76      7781